### ISSUE TITLE
"Error: Failed to get document because the client is offline" when using FireAdmin.io

### ISSUE THREAD

**Issue by laurendporteous** [prescottprue/fireadmin#116]
## Bug Description
I am experiencing a bug when first logging into the platform, where I am getting an “Error: Failed to get document because the client is offline” toast message. When I try to run an Action, it runs and then ends up failing and therefore, not migrating the campaign.

## Steps To Reproduce
Login to fireadmin.io
See an error will appear: “Error: Failed to get document because the client is offline.”
Go to Action Runner
Choose template: ‘Copy Firestore collection’
Add custom values

## Expected Behavior
The Actions should run and the campaigns be migrated successfully

## Additional Context/Screenshots
In the Project Events section, the system is showing an error. 
<img width="1107" alt="Screenshot 2020-06-12 at 1 55 12 pm" src="https://user-images.githubusercontent.com/46005222/84505068-01f34680-acb5-11ea-8dde-a0e807ae68ea.png">

**Comment by prescottprue** [comment]
Thanks for reaching out! That is definitely not expected, I'll look into replicating - I actually was seeing that client offline error in Sentry as well

**Comment by laurendporteous** [comment]
Hello!

Sorry about the late response. 

- Browser: Google Chrome [Version 83.0.4103.97 (Official Build) (64-bit)]
- No Ad Blockers
- I've used FireAdmin many times in the past and it always worked without issue!

Thanks!

**Comment by laurendporteous** [comment]
Hi! Just wondering if you have any update on this?

**Comment by prescottprue** [comment]
@laurendporteous I have still not been able to replicate either issue on my end. I believe that they are separate, so could you give running the action to copy Firestore data another try? Then if the error pops up again, there is a little more to go on

Something else I was wondering is if you are sure that they service accounts you used to setup your environments still have read/write access to your DB - guessing you have already confirmed that though?

**Comment by laurendporteous** [comment]
It is working now!

**Comment by prescottprue** [comment]
Weird... Ok, I think I might be able to track the change that was causing that, believe it may be in the functions. Either way though I'll make sure the unit tests cover that case. Thanks a bunch for reporting with so much detail!

Assuming the login issue is also resolved? Going to close for now, but let me know if anything else isn't working perfectly - been overhauling some stuff recently in preparation for some new features
