### ISSUE TITLE
still using "fireadmin"?

### ISSUE THREAD

**Issue by ksnyde** [prescottprue/fireadmin#2]
Scott,

I see you're work revolves around similar concerns to mine (redux and firebase anyway). I imagine that you may still be using this repo but since there were no recent commits to it I thought I'd ask because I have **firemodel** and **firemock** which i'm currently developing and purely from a naming convention standpoint I'd love to have **fireadmin** for a private repo I'd like to OSS. That said, if you're using it I can just find another name.

**Comment by prescottprue** [comment]
@ksnyde There are still a few places where `fireadmin` is being used in applications that are in production. Others may still depend on it as well, not totally sure (wouldn't be that easy to find out).

Does what your developing have any similarities? Always open to pull requests and updates.

**Comment by ksnyde** [comment]
Sure that makes sense Scott. I just wanted to check. My code is similar yet different enough that it probably doesn't fit as a PR.

I must say I love your tech focus around redux and Firebase; any illusions that my brilliant ideas were somehow unique to me have been stripped in seeing some of your repos. :)

Good luck with everything.

--
Ken Snyder
