### ISSUE TITLE
Can we add docker support ?

### ISSUE THREAD

**Issue by bnap00** [prescottprue/fireadmin#28]
Adding docker support would help people to quickly deploy, make a quick change and clear the environment and it could also help in dependency management as well.

**Comment by prescottprue** [comment]
Added initial support [in this pull request](https://github.com/prescottprue/fireadmin/pull/48). It basically just builds then calls a static file server. As mentioned, there is most likely room for a containerized approach around the other pieces of the application as well.

Thanks for reaching out with the suggestion. Reach out if it doesn't work as you expect or if you are looking for something more specific in the Docker setup.
