### ISSUE TITLE
key elements in table of contents are missing

### ISSUE THREAD

**Issue by bnap00** [prescottprue/fireadmin#9]
In the main README.md, some key elements from table of contents are missing. For example, getting started is missing. I am not able to get it working on my local system and having something like getting started would be a nice welcome. 
Thanks.

**Comment by prescottprue** [comment]
@bnap00 Thanks for checking out the project! I've mostly been working on getting things up and running on [fireadmin.io](http://fireadmin.io), so haven't gotten to the README too much yet (it is from me running [generator-react-fireabse](http://github.com/prescottprue/generator-react-firebaes) to start this project).

Would love to hear more about what you are looking for within a Firebase application manager. I have tons of ideas and would love to bounce around ideas. If you are on [gitter](gitter.im/redux-firebase/Lobby), we can chat on there, but I am actually working on a list of features to add to [this pr](https://github.com/prescottprue/fireadmin/pull/8).
