### ISSUE TITLE
fireadmin.io is blank

### ISSUE THREAD

**Issue by niklasravnsborg** [prescottprue/fireadmin#92]
## Bug Description
In the current Chrome version (77) the fireadmin.io website is completely blank (see screenshot). It works fine with Firefox and Safari. The console outputs the following error messages:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Uncaught ReferenceError: Raven is not defined
```

## Expected Behavior
I expect to see some content.

## Additional Context/Screenshots

<img width="1552" alt="Screenshot 2019-09-30 at 08 30 42" src="https://user-images.githubusercontent.com/6717303/65854380-c306a600-e35c-11e9-8652-18abbfc2a8ad.png">

**Comment by prescottprue** [comment]
Thanks for reporting! It seems like for some reason that chrome is blocking the request for Raven. Do you have some sort of plugin running that blocks analytics and/or error reporting?

Either way, in [an update that is coming soon](https://github.com/prescottprue/fireadmin/pull/84), I switched things over [to using the `@sentry/browser`](https://github.com/prescottprue/fireadmin/pull/84/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40) npm package which means that this code will be part of the bundle, and this request to get Raven will no longer be going out (Raven isn't even used anymore).

**Comment by niklasravnsborg** [comment]
> Thanks for reporting! It seems like for some reason that chrome is blocking the request for Raven. Do you have some sort of plugin running that blocks analytics and/or error reporting?
> 
> Either way, in [an update that is coming soon](https://github.com/prescottprue/fireadmin/pull/84), I switched things over [to using the `@sentry/browser`](https://github.com/prescottprue/fireadmin/pull/84/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40) npm package which means that this code will be part of the bundle, and this request to get Raven will no longer be going out (Raven isn't even used anymore).

Yes indeed. I have the privacy extension by DuckDuckGo installed: https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg

I didn't notice that it was also running in incognito mode.

**Comment by prescottprue** [comment]
The change to @sentry/browser was made some time ago. Please open another issue with the error message if you are still experiencing things being blocked, thanks for reporting!
